### PR TITLE
Add serial monitor settings on Home panel.

### PR DESCRIPTION
**Pull request by rudeb0t**
Re #15

### CODE REVIEW

**Comment by thelastoutpostworkshop** [comment]
Good Job!

**Review by thelastoutpostworkshop — APPROVED** [review]

**Comment by thelastoutpostworkshop** [comment]
@rudeb0t I was wondering if you see a use case where the port to upload and the port in serial monitoring could be different ?
I was thinking of having the port for upload and serial monitor to be the same,

**Comment by rudeb0t** [comment]
> @rudeb0t I was wondering if you see a use case where the port to upload and the port in serial monitoring could be different ? I was thinking of having the port for upload and serial monitor to be the same,

On macOS this is the case. `/dev/cu.*` is where you upload and `/dev/tty.*` is where you connect to the serial port. Initially I had it set up to use the same port `/dev/cu.SLAB_USBtoUART` for both upload and serial monitor. Whenever I upload a sketch, the serial monitor fails to connect to the port saying it's not connected to the device. After a bit of searching, I found [this](https://pbxbook.com/other/mac-tty.html) where it says `/dev/cu.*` and `/dev/tty.*` are different things. The subtle difference is `/dev/cu.*` does not wait for CDC and this causes the vscode serial monitor extension to fail to connect to it saying the device is not connected. The `/dev/cu.*` ports are also not listed in the dropdown in the extension:
image
And so even though it's more work, I added a separate serial monitor port field.

**Comment by thelastoutpostworkshop** [comment]
That makes sense, thanks for the explanation.

**Pull request merged**
